home/views.py
import json
import os
import uuid
from datetime import datetime
from io import BytesIO

from flask import Blueprint, render_template, redirect, url_for, flash, make_response, session, request, Response
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename

from conf import Config
from home.forms import RegisterForm, LoginForm, UserDetailForm, ModifyPasswordForm, CommentForm
from models import User, db, UserLog, Preview, Tag, Movie, Comment, MovieCollect, rd
from utils.decorator import user_login_req
from utils.filters import change_filename
from utils.utils import get_verify_code, user_login_log

home = Blueprint('home', __name__,
                 template_folder='templates/',
                 static_folder='../static/home')


# 登录验证码
@home.route('/code')
def get_code():
    image, code = get_verify_code()
    # 图片以二进制形式写入
    buf = BytesIO()
    image.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    # 把buf_str作为response返回前端，并设置首部字段
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/gif'
    # 将验证码字符串储存在session中
    session['image'] = code
    return response


# 首页
@home.route('/<int:page>/', methods=['GET'])
@home.route('/index/<int:page>/', methods=['GET'])
def index(page=1):
    tags = Tag.query.all()
    page_data = Movie.query

    # 标签
    tid = int(request.args.get('tid', 0))
    if tid != 0:
        page_data = page_data.filter_by(tag_id=tid)
    # 星级
    star = int(request.args.get('star', 0))
    if star != 0:
        page_data = page_data.filter_by(star=star)
    # 时间
    time = int(request.args.get('time', 0))
    if time != 0:
        if time == 1:
            page_data = page_data.order_by(Movie.created_at.desc())
        elif time == 2:
            page_data = page_data.order_by(Movie.created_at.asc())

    # 播放量
    pm = int(request.args.get('pm', 0))
    if pm != 0:
        if pm == 1:
            page_data = page_data.order_by(Movie.play_count.desc())
        elif pm == 2:
            page_data = page_data.order_by(Movie.play_count.asc())

    # 评论量
    cm = int(request.args.get('cm', 0))
    if cm != 0:
        if cm == 1:
            page_data = page_data.order_by(Movie.comment_count.desc())
        elif cm == 2:
            page_data = page_data.order_by(Movie.comment_count.asc())

    page_data = page_data.paginate(page=page, per_page=Config.PER_PAGE)

    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )

    return render_template('home_index.html', tags=tags, p=p, page_data=page_data)


# 搜索
@home.route('/search/<int:page>', methods=['GET'])
def search(page=1):
    key = request.args.get('key', '')
    movie_obj = Movie.query.filter(Movie.name.ilike('%' + key + '%'))
    movie_count = movie_obj.count()
    page_data = movie_obj.order_by(Movie.created_at.desc()).paginate(page=page, per_page=Config.PER_PAGE)
    page_data.key = key
    return render_template('home_search.html', key=key, page_data=page_data, movie_count=movie_count)


# 上映预告
@home.route('/animation/', methods=['GET'])
def animation():
    data = Preview.query.all()
    return render_template('home_animation.html', data=data)


# 电影详情
@home.route('/movie_detail/<int:movie_id>/<int:page>/', methods=['GET', 'POST'])
def movie_detail(movie_id=None, page=1):
    movie_obj = Movie.query.get_or_404(int(movie_id))

    form = CommentForm()
    if form.validate_on_submit():
        if session['user']:
            data = form.data
            comment_obj = Comment(
                content=data['content'],
                movie_id=movie_id,
                user_id=session['user_id'],
            )
            db.session.add(comment_obj)
            movie_obj.comment_count = movie_obj.comment_count + 1
            db.session.add(movie_obj)

            db.session.commit()
            flash('评论成功', 'success')
            return redirect(url_for('home.movie_detail', movie_id=movie_id, page=1))

    movie_obj.play_count = movie_obj.play_count + 1
    db.session.add(movie_obj)
    db.session.commit()

    page_data = Comment.query.filter_by(movie_id=movie_id).order_by(Comment.created_at.desc(),
                                                                    Comment.id.desc()).paginate(page=page,
                                                                                                per_page=Config.PER_PAGE)

    return render_template('home_movie_detail.html', movie_obj=movie_obj, form=form, page_data=page_data)


# 电影详情_弹幕
@home.route('/video/<int:movie_id>/<int:page>/', methods=['GET', 'POST'])
def video(movie_id=None, page=1):
    movie_obj = Movie.query.get_or_404(int(movie_id))

    form = CommentForm()
    if session['user'] and form.validate_on_submit():
        data = form.data
        comment_obj = Comment(
            content=data['content'],
            movie_id=movie_id,
            user_id=session['user_id'],
        )
        db.session.add(comment_obj)
        movie_obj.comment_count = movie_obj.comment_count + 1
        db.session.add(movie_obj)

        db.session.commit()
        flash('评论成功', 'success')
        return redirect(url_for('home.video', movie_id=movie_id, page=1))

    movie_obj.play_count = movie_obj.play_count + 1
    db.session.add(movie_obj)
    db.session.commit()

    page_data = Comment.query.filter_by(movie_id=movie_id).order_by(Comment.created_at.desc(),
                                                                    Comment.id.desc()).paginate(page=page,
                                                                                                per_page=Config.PER_PAGE)

    return render_template('home_video.html', movie_obj=movie_obj, form=form, page_data=page_data)


# 登录
@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user_obj = User.query.filter_by(username=data['username']).first()
        if user_obj is None:
            flash('用户不存在', 'danger')
            return render_template('home_login.html', form=form)
        if not user_obj.check_password(data['password']):
            flash('密码错误', 'danger')
            return render_template('home_login.html', form=form)
        if session.get('image').lower() != data['verify_code'].lower():
            flash('验证码错误！', 'danger')
            return render_template('home_login.html', form=form)
        session['user'] = user_obj.username
        session['user_id'] = user_obj.id

        login_type = 'PC'
        user_login_log_obj = user_login_log(login_type)
        db.session.add(user_login_log_obj)
        db.session.commit()
        return redirect(url_for('home.member_center'))
    return render_template('home_login.html', form=form)


# 退出
@home.route('/logout/', methods=['GET'])
@user_login_req
def logout():
    session.pop('user', None)
    session.pop('user_id', None)
    return redirect(url_for('home.login'))


# 会员注册
@home.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user_obj = User(username=data['username'], password=generate_password_hash(data['password']),
                        email=data['email'], phone=data['phone'], nickname=data['nickname'], uuid=uuid.uuid4().hex)
        try:
            db.session.add(user_obj)
            db.session.commit()
            flash('注册成功！', 'success')
            return redirect(url_for('home.login'))
        except Exception as e:
            flash('注册失败！', 'danger')

    return render_template('home_register.html', form=form)


# 个人中心
@home.route('/member_center/', methods=['GET', 'POST'])
@user_login_req
def member_center():
    form = UserDetailForm()
    user_obj = User.query.get(int(session['user_id']))
    form.avatar.validators = []
    if request.method == 'GET':
        form.info.data = user_obj.info

    if form.validate_on_submit():
        data = form.data

        if form.avatar.data.filename != '':
            file_avatar = secure_filename(form.avatar.data.filename)
            # 如果不存在目录，则创建并授权
            if not os.path.exists(Config.UPLOADS_DIR):
                os.makedirs(Config.UPLOADS_DIR)
                os.chmod(Config.UPLOADS_DIR, 6)

            # 格式化名字并保存文件
            avatar = change_filename(file_avatar)
            form.avatar.data.save(Config.UPLOADS_DIR + 'user/avatar/' + avatar)
            user_obj.avatar = avatar

        email_count = User.query.filter_by(email=data['email']).count()
        if data['email'] != user_obj.email and email_count == 1:
            flash('该邮箱已经存在', 'danger')
            return redirect(url_for('home.member_center'))

        phone_count = User.query.filter_by(phone=data['phone']).count()
        if data['phone'] != user_obj.phone and phone_count == 1:
            flash('该手机号码已经存在', 'danger')
            return redirect(url_for('home.member_center'))

        user_obj.username = session['user']
        user_obj.email = data['email']
        user_obj.phone = data['phone']
        user_obj.info = data['username']
        user_obj.nickname = data['nickname']
        db.session.add(user_obj)
        db.session.commit()
        flash('修改成功！', 'success')
        return redirect(url_for('home.member_center'))

    return render_template('home_member_center.html', form=form, user_obj=user_obj)


# 修改密码
@home.route('/edit_password/', methods=['GET', 'POST'])
@user_login_req
def edit_password():
    form = ModifyPasswordForm()
    if form.validate_on_submit():
        user_obj = User.query.filter_by(username=session['user']).first()
        user_obj.password = generate_password_hash(form.pwd.data)

home/templates/home_animation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>热映电影</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css') }}">
    {#    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home/animation/css/style.css') }}">#}
</head>
<body>
<!--轮播图 开始 -->
{#<div class="main_banner">#}
{#    <div class="main_banner_wrap">#}
{#        <canvas id="myCanvas" width="150" height="150"></canvas>#}
{#        <div class="main_banner_box" id="m_box">#}
{#            <a href="javascript:void(0)" class="banner_btn js_pre">#}
{#                <span class="banner_btn_arrow"><i></i></span>#}
{#            </a>#}
{#            <a href="javascript:void(0)" class="banner_btn btn_next js_next">#}
{#                <span class="banner_btn_arrow"><i></i></span>#}
{#            </a>#}
{#            <ul>#}
{#                {% for item in data %}#}
{#                    <li id="imgCard{{ item.id }}">#}
{#                        <a href="javascript:;"><span style="opacity:0;"></span></a>#}
{#                        <img src="{{ url_for('static', filename='uploads/' + item.logo) }}" alt="">#}
{#                        <p style="bottom:0">{{ item.name }}</p>#}
{#                    </li>#}
{#                {% endfor %}#}
{#            </ul>#}
{#            <!--火狐倒影图层-->#}
{#            <p id="rflt"></p>#}
{#            <!--火狐倒影图层-->#}
{#        </div>#}
{#        <!--序列号按钮-->#}
{#        <div class="btn_list">#}
{#            <span class="curr"></span><span></span><span></span><span></span><span></span>#}
{#        </div>#}
{#    </div>#}
{##}
{#</div>#}
<!--轮播图 结束 -->


<!-- bootstrap轮播图 开始 -->
    <div id="carousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            {% for item in data %}
                <li data-target="#carousel" data-slide-to="{{ item.id - 1 }}"></li>
            {% endfor %}
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            {% for item in data %}
                <div class="item">
                    <img style="height: 900px;" class="img-responsive center-block"
                         src="{{ url_for('static', filename='uploads/' + item.logo) }}" alt="{{ item.name }}">
                    <div class="carousel-caption" style="background-color: #000; opacity: 0.6;">
                        <h3>{{ item.name }}</h3>
                        <p>{{ item.info|truncate(59, killwords=True, leeway=0) }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
<!-- bootstrap轮播图 结束-->

{#<script type="text/javascript" src="{{ url_for('static', filename='home/animation/js/jquery.js') }}"></script>#}
{#<script type="text/javascript" src="{{ url_for('static', filename='home/animation/js/script.js') }}"></script>#}
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script>
    $(document).ready(() => {
        $('.carousel-indicators > li:first-child').toggleClass('active')
        $('.carousel-inner > div:first-child').toggleClass('active')
    })
</script>
</body>
</html>

home/templates/home_comments.html
{% extends 'home_base.html' %}
{% from 'macro/page_nav.html' import page_nav %}
{% block title %}评论记录{% endblock %}
{% block content %}
    {% include 'components/home_nav.html' %}
    <div class="container" style="margin-top:76px">
        <div class="row">
            {% include 'components/home_user_menu.html' %}
            <div class="col-md-9">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;评论记录</h3>
                    </div>
                    <div class="panel-body">
                        <ul class="commentList">
                            {% for item in page_data.items %}
                                <li class="item cl">
                                    <a href="user.html">
                                        <i class="avatar size-L radius">
                                            {% if item.user.avatar %}
                                                <img alt="{{ item.user.username }}"
                                                     src="{{ url_for('static', filename='uploads/user/avatar/' + item.user.avatar) }}"
                                                     class="img-circle"
                                                     style="border:1px solid #abcdef; width: 50px; height: 50px;">
                                            {% else %}
                                                <img alt="50x50"
                                                     data-src="holder.js/50x50"
                                                     class="img-circle"
                                                     style="border:1px solid #abcdef; width: 50px; height: 50px;">
                                            {% endif %}

                                        </i>
                                    </a>
                                    <div class="comment-main">
                                        <header class="comment-header">
                                            <div class="comment-meta">
                                                <a class="comment-author"
                                                   href="javascript:;">{{ item.user.username }}</a>
                                                于
                                                <time title="2016-12-07 09:12:51" datetime="2016-12-07 09:12:51">
                                                    {{ item.created_at }}
                                                </time>
                                                评论电影：
                                                <a href="{{ url_for('home.movie_detail', movie_id=item.movie_id, page=1) }}">{{ item.movie.name }}</a>
                                            </div>
                                        </header>
                                        <div class="comment-body">
                                            <p>{{ item.content|safe }}</p>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                        <div class="col-md-12">
                            {{ page_nav(page_data, 'home.comments') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(() => {
            $("#m-3").addClass("active");
        })
    </script>
{% endblock %}

home/templates/home_index.html
{% extends 'home_base.html' %}
{% from 'macro/page_nav.html' import page_nav %}
{% block content %}
    {% include 'components/home_nav.html' %}
    <!--热门电影-->
    <section id="hotmovie" style="margin-top:76px">
        <div class="container-fluid">
            <div class="row wow fadeInRight" data-wow-delay="0.6s">
                    <iframe class="wow fadeIn" width="100%" height="900px" frameborder=0 scrolling=no
                            src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </section>
    <!--热门电影-->
    <!--电影列表-->
    <section id="movielist">
        <div class="container">
            <div class="row wow fadeIn" data-wow-delay="0.6s">
                <div class="col-md-12 table-responsive">
                    <table class="table text-left table-bordered" id="movietags">
                        <tr>
                            <td style="width:10%;">电影标签</td>
                            <td style="width:90%;">
                                {% for item in tags %}
                                    <a href="{{ url_for('home.index', page=1) }}?tid={{ item.id }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                                       class="label label-info"><span
                                            class="glyphicon glyphicon-tag"></span>&nbsp;{{ item.name }}</a>
                                    &nbsp;
                                {% endfor %}
                        </tr>
                        <tr>
                            <td>电影星级</td>
                            <td>
                                {% for item in range(1, 6) %}
                                    <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ item }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                                       class="label label-warning"><span
                                            class="glyphicon glyphicon-star"></span>&nbsp;{{ item }}星</a>
                                    &nbsp;{% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td>上映时间</td>
                            <td>
                                <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=1&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                                   class="label label-default"><span
                                        class="glyphicon glyphicon-time"></span>&nbsp;最近</a>
                                &nbsp;
                                <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=2&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                                   class="label label-default"><span
                                        class="glyphicon glyphicon-time"></span>&nbsp;更早</a>
                            </td>
                        </tr>
                        <tr>
                            <td>播放数量</td>
                            <td>
                                <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=1&cm={{ p['cm'] }}"
                                   class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底
                                </a>
                                &nbsp;
                                <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=2&cm={{ p['cm'] }}"
                                   class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>评论数量</td>
                            <td>
                                <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=1"
                                   class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底
                                </a>
                                &nbsp;
                                <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=2"
                                   class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
                {% for item in page_data.items %}
                    <div class="col-md-3">
                        <div class="movielist text-center">
                            <!--<img data-original="holder.js/262x166"
                                     class="img-responsive lazy center-block" alt="">-->
                            <img style="height: 175px;" src="{{ url_for('static', filename='uploads/' + item.logo) }}"
                                 class="img-responsive center-block" alt="">
                            <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                                <span style="color:#999;font-style: italic;">{{ item.name|truncate(18) }}</span><br>
                                <div>
                                    {% for _ in range(1, item.star + 1) %}
                                        <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                                    {% endfor %}
                                    {% for _ in range(1, 6 - item.star) %}
                                        <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                                    {% endfor %}
                                </div>
                            </div>
                            <a href="{{ url_for('home.movie_detail', movie_id=item.id, page=1) }}"
                               class="btn btn-primary"
                               target="_blank"
                               role="button"><span
                                    class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                        </div>
                    </div>
                {% endfor %}
                <div class="col-md-12">
                    {{ page_nav(page_data, 'home.index') }}
                </div>
            </div>
        </div>
    </section>
    <!--电影列表-->
{% endblock %}

home/templates/home_login.html
{% extends 'home_base.html' %}
{% from 'macro/form_errors.html' import form_field_errors %}
{% block title %}用户登录{% endblock %}

{% block content %}
    <div class="container" style="margin-top:120px">
        {% include 'components/flash_messages.html' %}
        <h2 class="text-center">欢迎来到LGSP微电影</h2>
        <hr>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-log-in"></span>&nbsp;会员登录</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" action="" method="post">
                            {{ form.csrf_token }}
                            <fieldset>
                                <div class="form-group">
                                    <label for="input_contact"><span
                                            class="glyphicon glyphicon-user"></span>&nbsp;{{ form.username.label.text }}
                                    </label>
                                    {{ form.username }}
                                    {{ form_field_errors(form.username.error) }}
                                </div>
                                <div class="form-group">
                                    <label for="input_password"><span
                                            class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.password.label.text }}
                                    </label>
                                    {{ form.password }}
                                    {{ form_field_errors(form.password.error) }}
                                </div>
                                <div class="form-group">
                                    <label for="input_password"><span
                                            class="glyphicon glyphicon-check"></span>&nbsp;{{ form.verify_code.label.text }}
                                    </label>
                                    <div class="row">
                                        <div class="col-xs-6 col-sm-9">{{ form.verify_code }}</div>
                                        <div class="col-xs-6 col-sm-3">
                                            <img class="verify_code" src="/code"
                                                 onclick="this.src='/code?'+ Math.random()">
                                        </div>
                                        {{ form_field_errors(form.verify_code.error) }}
                                    </div>
                                </div>
                                {{ form.submit }}
                                <hr>
                                <div class="pull-left"><label><a href="{{ url_for('home.index', page=1) }}">返回首页</a></label>
                                </div>
                                <div class="pull-right"><label>未有账号？立即<a
                                        href="{{ url_for('home.register') }}">注册</a></label></div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home_register.html
{% extends 'home_base.html' %}
{% from 'macro/form_errors.html' import form_field_errors %}
{% block title %}用户注册{% endblock %}

{% block content %}
    <div class="container" style="margin-top:120px">
        {% include 'components/flash_messages.html' %}
        <h2 class="text-center">欢迎注册LGSP微电影</h2>
        <hr>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-plus"></span>&nbsp;会员注册</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="">
                            {{ form.csrf_token }}
                            <fieldset>
                                <div class="form-group">
                                    <label><span
                                            class="glyphicon glyphicon-user"></span>&nbsp;{{ form.username.label.text }}
                                    </label>
                                    {{ form.username }}
                                    {{ form_field_errors(form.username.errors) }}
                                </div>
                                <div class="form-group">
                                    <label><span
                                            class="glyphicon glyphicon-envelope"></span>&nbsp;{{ form.email.label.text }}
                                    </label>
                                    {{ form.email }}
                                    {{ form_field_errors(form.email.errors) }}
                                </div>
                                <div class="form-group">
                                    <label><span
                                            class="glyphicon glyphicon-phone"></span>&nbsp;{{ form.phone.label.text }}
                                    </label>
                                    {{ form.phone }}
                                    {{ form_field_errors(form.phone.errors) }}

                                </div>
                                <div class="form-group">
                                    <label for="input_password"><span
                                            class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.password.label.text }}
                                    </label>
                                    {{ form.password }}
                                    {{ form_field_errors(form.password.errors) }}
                                </div>
                                <div class="form-group">
                                    <label for="input_re_password"><span
                                            class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.re_password.label.text }}
                                    </label>
                                    {{ form.re_password }}
                                    {{ form_field_errors(form.re_password.errors) }}
                                </div>
                                {{ form.submit }}
                                <hr>
                                <div class="pull-left"><label><a href="{{ url_for('home.index', page=1) }}">返回首页</a></label>
                                </div>
                                <div class="pull-right"><label>已有账号？立即<a
                                        href="{{ url_for('home.login') }}">登录</a></label></div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}