admin/views.py
import os
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename

import constants
from admin.forms import LoginForm, TagForm, MovieForm, PreviewForm, ModifyPasswordForm, AuthForm, RoleForm, AdminForm

from conf import Config
from models import db, Tag, Movie, Preview, User, Comment, MovieCollect, Admin, AdminOperateLog, AdminLog, UserLog, \
    Auth, Role
from utils.filters import change_filename
from utils.decorator import admin_login_req, admin_auth
from utils.utils import admin_operate_log, admin_login_log

admin = Blueprint('admin', __name__,
                  template_folder='templates',
                  static_folder='../static/admin')


# 上下文处理器
@admin.context_processor
def tpl_extra():
    data = dict(
        online_time=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    )
    return data


@admin.route('/')
@admin_login_req
@admin_auth
def index():
    return render_template('admin_index.html')


# 登录
@admin.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        admin_obj = Admin.query.filter_by(username=data['username']).first()
        # if not admin.check_password(data['password']):
        #     flash('密码错误', 'danger')
        #     return redirect(url_for('admin.login'))
        session['admin'] = data['username']
        session['admin_id'] = admin_obj.id

        admin_login_log_obj = admin_login_log()
        db.session.add(admin_login_log_obj)
        db.session.commit()

        return redirect(request.args.get('next') or url_for('admin.index'))
    return render_template('admin_login.html', form=form)


# 退出
@admin.route('/logout/', methods=['GET'])
@admin_login_req
def logout():
    session.pop('admin', None)
    session.pop('admin_id', None)
    return redirect(url_for('admin.login'))


# 修改密码
@admin.route('/edit_password/', methods=['GET', 'POST'])
@admin_login_req
def edit_password():
    form = ModifyPasswordForm()
    if form.validate_on_submit():
        try:
            admin_obj = Admin.query.filter_by(username=session['admin']).first()
            if admin_obj is None:
                flash('登录失效，请重新登录！', 'danger')
                return redirect(url_for('admin.login'))
            admin_obj.password = generate_password_hash(form.pwd.data)
            db.session.add(admin_obj)
            reason = '修改密码'
            admin_operate_log_obj = admin_operate_log(reason)
            db.session.add(admin_operate_log_obj)

            db.session.commit()
            flash('密码修改成功,请重新登录', 'success')
            return redirect(url_for('admin.logout'))
        except Exception as e:
            flash('服务器忙，请联系管理员或稍后重试！', 'danger')
            return redirect(url_for('admin.index'))
    return render_template('admin_edit_password.html', form=form)


# 添加标签
@admin.route('/tag_add/', methods=['GET', 'POST'])
@admin_login_req
@admin_auth
def tag_add():
    form = TagForm()
    if form.validate_on_submit():
        name = form.name.data
        try:
            tag_obj = Tag(name=name)
            db.session.add(tag_obj)

            reason = '添加标签：%s' % name
            admin_operate_log_obj = admin_operate_log(reason)
            db.session.add(admin_operate_log_obj)

            db.session.commit()
            flash('添加成功', 'success')
            return redirect(url_for('admin.tag_list', page=1))
        except Exception as e:
            flash('服务器忙，请联系管理员或稍后重试！', 'danger')
            return redirect(url_for('admin.tag_add'))
    return render_template('admin_tag_add.html', form=form)


# 编辑标签
@admin.route('/tag_edit/<int:tag_id>/', methods=['GET', 'POST'])
@admin_login_req
@admin_auth
def tag_edit(tag_id):
    form = TagForm()
    tag_obj = Tag.query.get(tag_id)
    if form.validate_on_submit():
        name = form.name.data
        tag_count = Tag.query.filter_by(name=name).count()
        if tag_obj.name != name and tag_count == 1:
            flash('标签已存在', 'warning')
            return redirect(url_for('admin.tag_edit', tag_id=tag_id))
        try:
            tag_obj.name = name
            db.session.add(tag_obj)

            reason = '修改标签为：%s' % name
            admin_operate_log_obj = admin_operate_log(reason)
            db.session.add(admin_operate_log_obj)

            db.session.commit()
            flash('标签修改成功', 'success')
            return redirect(url_for('admin.tag_list', page=1))
        except Exception as e:
            flash('服务器忙，请联系管理员或稍后重试！', 'danger')
            return redirect(url_for('admin.tag_list', page=1))
    return render_template('admin_tag_edit.html', form=form, tag_obj=tag_obj)


# 标签列表
@admin.route('/tag_list/<int:page>/', methods=['GET'])
@admin_login_req
@admin_auth
def tag_list(page=1):
    page_data = Tag.query.order_by(Tag.created_at.desc(), Tag.id.desc()).paginate(page, per_page=Config.PER_PAGE)
    return render_template('admin_tag_list.html', page_data=page_data)


# 删除标签
@admin.route('/tag_del/<int:tag_id>/', methods=['GET'])
@admin_login_req
@admin_auth
def tag_del(tag_id):
    tag_obj = Tag.query.filter_by(id=tag_id).first()
    if not tag_obj:
        flash('查询不到标签，请刷新后重试！', 'warning')
        return redirect(url_for('admin.tag_list', page=1))
    else:
        db.session.delete(tag_obj)

        reason = '删除标签'
        admin_operate_log_obj = admin_operate_log(reason)
        db.session.add(admin_operate_log_obj)

        db.session.commit()
        flash('标签：{}，删除成功！'.format(tag_obj.name), 'success')
        return redirect(url_for('admin.tag_list', page=1))


# 添加电影
@admin.route('/movie_add/', methods=['GET', 'POST'])
@admin_login_req
@admin_auth
def movie_add():
    form = MovieForm()
    form.tag_id.choices = [(v.id, v.name) for v in Tag.query.all()]
    if form.validate_on_submit():
        data = form.data
        # 重置为安全的文件名
        file_url = secure_filename(form.url.data.filename)
        file_logo = secure_filename(form.logo.data.filename)

        # 如果不存在目录，则创建并授权
        if not os.path.exists(Config.UPLOADS_DIR):
            os.makedirs(Config.UPLOADS_DIR)
            os.chmod(Config.UPLOADS_DIR, 6)

        # 格式化名字并保存文件
        url = change_filename(file_url)
        logo = change_filename(file_logo)
        form.url.data.save(Config.UPLOADS_DIR + url)
        form.logo.data.save(Config.UPLOADS_DIR + logo)

        movie = Movie(
            name=data['name'],
            url=url,
            info=data['info'],
            logo=logo,
            star=int(data['star']),
            play_count=0,
            comment_count=0,
            tag_id=int(data['tag_id']),
            area=data['area'],
            release_date=data['release_date'],
            movie_length=data['movie_length']
        )
        try:
            db.session.add(movie)

            reason = '添加电影：%s' % data['name']
            admin_operate_log_obj = admin_operate_log(reason)
            db.session.add(admin_operate_log_obj)

            db.session.commit()
            flash('添加电影成功', 'success')
            return redirect(url_for('admin.movie_list', page=1))
        except Exception as e:
            flash('添加电影失败', 'error')
    return render_template('admin_movie_add.html', form=form)


# 编辑电影
@admin.route('/movie_edit/<int:movie_id>/', methods=['GET', 'POST'])
@admin_login_req
@admin_auth
def movie_edit(movie_id):
    form = MovieForm()
    form.tag_id.choices = [(v.id, v.name) for v in Tag.query.all()]

    # form.url.validators = []
    # form.logo.validators = []
    movie_obj = Movie.query.get(movie_id)

    if request.method == 'GET':
        form.info.data = movie_obj.info
        form.tag_id.data = movie_obj.tag_id
        form.star.data = movie_obj.star
    if form.validate_on_submit():
        data = form.data
        try:
            # 如果不存在目录，则创建并授权
            if not os.path.exists(Config.UPLOADS_DIR):
                os.makedirs(Config.UPLOADS_DIR)
                os.chmod(Config.UPLOADS_DIR, 6)

            if form.url.data.filename != '':
                file_url = secure_filename(form.url.data.filename)
                url = change_filename(file_url)
                form.url.data.save(Config.UPLOADS_DIR + url)
                movie_obj.url = url

            if form.logo.data.filename != '':
                file_logo = secure_filename(form.logo.data.filename)
                logo = change_filename(file_logo)
                form.logo.data.save(Config.UPLOADS_DIR + logo)
                movie_obj.logo = logo

            movie_obj.name = data['name']
            movie_obj.info = data['info']
            movie_obj.area = data['area']
            movie_obj.release_date = data['release_date']
            movie_obj.movie_length = data['movie_length']
            movie_obj.star = int(data['star']),
            movie_obj.tag_id = int(data['tag_id'])
            db.session.add(movie_obj)

            reason = '修改电影：%s' % data['name']
            admin_operate_log_obj = admin_operate_log(reason)
            db.session.add(admin_operate_log_obj)

            db.session.commit()
            flash('电影修改成功', 'success')
            return redirect(url_for('admin.movie_list', page=1))
        except Exception as e:
            flash('服务器忙，请联系管理员或稍后重试！', 'danger')
            return redirect(url_for('admin.movie_list', page=1))
    return render_template('admin_movie_edit.html', form=form, movie_obj=movie_obj)


# 电影列表
@admin.route('/movie_list/<int:page>/', methods=['GET'])
@admin_login_req
@admin_auth
def movie_list(page=1):

admin/templates/admin_auth_add.html
{% extends 'admin_base.html' %}
{% block content %}
    {% include 'components/admin_nav.html' %}
    {% include 'components/admin_aside_menu.html' %}
    <div class="content-wrapper">
        <!--内容-->
        <section class="content-header">
            <h1>微电影管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 权限管理</a></li>
                <li class="active">添加权限</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">添加权限</h3>
                        </div>
                        <form role="form">
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="input_name">权限名称</label>
                                    <input type="text" class="form-control" id="input_name" placeholder="请输入权限名称！">
                                </div>
                                <div class="form-group">
                                    <label for="input_url">权限地址</label>
                                    <input type="text" class="form-control" id="input_url" placeholder="请输入权限地址！">
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">添加</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}
{% block js %}
    <script>
        $(() => {
            $('#g-9').addClass('active');
            $('#g-9-1').addClass('active');
        })
    </script>
{% endblock %}

admin/templates/admin_auth_edit.html
{% extends 'admin_base.html' %}
{% from 'macro/form_errors.html' import form_field_errors %}
{% block content %}
    {% include 'components/admin_nav.html' %}
    {% include 'components/admin_aside_menu.html' %}
    <div class="content-wrapper">
        {% include 'components/flash_messages.html' %}
        <!--内容-->
        <section class="content-header">
            <h1>微电影管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 权限管理</a></li>
                <li class="active">修改权限</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">修改权限</h3>
                        </div>
                        <form role="form" action="" method="post">
                            {{ form.csrf_token }}
                            <div class="box-body">
                                <div class="form-group">
                                    {{ form.name.label }}
                                    {{ form.name(value=auth_obj.name) }}
                                    {{ form_field_errors(form.name.errors) }}
                                </div>
                                <div class="form-group">
                                    {{ form.url.label }}
                                    {{ form.url(value=auth_obj.url) }}
                                    {{ form_field_errors(form.url.errors) }}
                                </div>
                            </div>
                            <div class="box-footer">
                                {{ form.submit }}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}
{% block js %}
    <script>
        $(() => {
            $('#g-9').addClass('active');
            $('#g-9-1').addClass('active');
        })
    </script>
{% endblock %}

admin/templates/admin_auth_list.html
{% extends 'admin_base.html' %}
{% from 'macro/page_nav.html' import page_nav %}
{% block content %}
    {% include 'components/admin_nav.html' %}
    {% include 'components/admin_aside_menu.html' %}
    <div class="content-wrapper">
    {% include 'components/flash_messages.html' %}
        <!--内容-->
        <section class="content-header">
            <h1>微电影管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 权限管理</a></li>
                <li class="active">权限列表</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <h3 class="box-title">权限列表</h3>
                            <div class="box-tools">
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="table_search" class="form-control pull-right"
                                           placeholder="请输入关键字...">

                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <tbody>
                                <tr>
                                    <th>编号</th>
                                    <th>权限名称</th>
                                    <th>权限路径</th>
                                    <th>添加时间</th>
                                    <th>操作事项</th>
                                </tr>
                                {% for item in page_data.items %}
                                <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.name }}</td>
                                    <td>{{ item.url }}</td>
                                    <td>{{ item.created_at }}</td>
                                    <td>
                                        <a href="{{ url_for('admin.auth_edit', auth_id=item.id) }}" class="label label-success">编辑</a>
                                        &nbsp;
                                        <a href="{{ url_for('admin.auth_del', auth_id=item.id) }}" class="label label-danger">删除</a>
                                    </td>
                                </tr>

                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer clearfix">
                            {{ page_nav(page_data, 'admin.auth_list') }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}
{% block js %}
    <script>
        $(() => {
            $('#g-9').addClass('active');
            $('#g-9-2').addClass('active');
        })
    </script>
{% endblock %}

admin/templates/admin_edit_password.html
{% extends 'admin_base.html' %}
{% from 'macro/form_errors.html' import form_field_errors %}
{% block content %}
    {% include 'components/admin_nav.html' %}
    {% include 'components/admin_aside_menu.html' %}
    <div class="content-wrapper">
        {% include 'components/flash_messages.html' %}
        <!--内容-->
        <section class="content-header">
            <h1>微电影管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 个人资料</a></li>
                <li class="active">修改密码</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">修改密码</h3>
                        </div>
                        <form role="form" method="post" action="">
                            {{ form.csrf_token }}
                            <div class="box-body">
                                <div class="form-group">
                                    {{ form.old_pwd.label }}
                                    {{ form.old_pwd }}
                                    {{ form_field_errors(form.old_pwd.errors) }}
                                </div>

                                <div class="form-group">
                                    {{ form.pwd.label }}
                                    {{ form.pwd }}
                                    {{ form_field_errors(form.pwd.errors) }}
                                </div>

                                <div class="form-group">
                                    {{ form.re_pwd.label }}
                                    {{ form.re_pwd }}
                                    {{ form_field_errors(form.re_pwd.errors) }}
                                </div>

                            </div>
                            <div class="box-footer">
                                {{ form.submit }}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}

admin/templates/admin_login_log_list.html
{% extends 'admin_base.html' %}
{% from 'macro/page_nav.html' import page_nav %}
{% block content %}
    {% include 'components/admin_nav.html' %}
    {% include 'components/admin_aside_menu.html' %}
    <div class="content-wrapper">
        {% include 'components/flash_messages.html' %}
        <!--内容-->
        <section class="content-header">
            <h1>微电影管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 日志管理</a></li>
                <li class="active">管理员登录日志列表</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <h3 class="box-title">管理员登录日志列表</h3>
                            <div class="box-tools">
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="table_search" class="form-control pull-right"
                                           placeholder="请输入关键字...">

                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <tbody>
                                <tr>
                                    <th>编号</th>
                                    <th>管理员</th>
                                    <th>登录时间</th>
                                    <th>登录IP</th>
                                    <th>登录终端</th>
                                </tr>
                                {% for item in page_data.items %}
                                    <tr>
                                        <td>{{ item.id }}</td>
                                        <td>{{ item.username }}</td>
                                        <td>{{ item.created_at }}</td>
                                        <td>{{ item.ip }}</td>
                                        <td>{{ item.ua }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer clearfix">
                            {{ page_nav(page_data, 'admin.admin_login_log_list') }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}
{% block js %}
    <script>
        $(() => {
            $('#g-8').addClass('active');
            $('#g-8-2').addClass('active');
        })
    </script>
{% endblock %}

admin/templates/admin_movie_list.html
{% extends 'admin_base.html' %}
{% from 'macro/page_nav.html' import page_nav %}
{% block content %}
    {% include 'components/admin_nav.html' %}
    {% include 'components/admin_aside_menu.html' %}
    <div class="content-wrapper">
        {% include 'components/flash_messages.html' %}
        <!--内容-->
        <section class="content-header">
            <h1>微电影管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 电影管理</a></li>
                <li class="active">电影列表</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <h3 class="box-title">电影列表</h3>
                            <div class="box-tools">
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="table_search" class="form-control pull-right"
                                           placeholder="请输入关键字...">

                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <tbody>
                                <tr>
                                    <th>编号</th>
                                    <th>片名</th>
                                    <th>片长</th>
                                    <th>标签</th>
                                    <th>地区</th>
                                    <th>星级</th>
                                    <th>播放数量</th>
                                    <th>评论数量</th>
                                    <th>上映时间</th>
                                    <th>操作事项</th>
                                </tr>
                                {% for item in page_data.items %}
                                    <tr>
                                        <td>{{ item.id }}</td>
                                        <td>{{ item.name }}</td>
                                        <td>{{ item.movie_length }}分钟</td>
                                        <td>{{ item.tag.name }}</td>
                                        <td>{{ item.area }}</td>
                                        <td>{{ item.star }}</td>
                                        <td>{{ item.play_count }}</td>
                                        <td>{{ item.comment_count }}</td>
                                        <td>{{ item.release_date }}</td>
                                        <td>
                                            <a href="{{ url_for('admin.movie_edit', movie_id=item.id) }}" class="label label-success">编辑</a>
                                            &nbsp;
                                            <a href="{{ url_for('admin.movie_del', movie_id=item.id) }}" class="label label-danger">删除</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer clearfix">
                            {{ page_nav(page_data, 'admin.movie_list') }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}
{% block js %}
    <script>
        $(() => {
            $('#g-3').addClass('active');
            $('#g-3-2').addClass('active');
        })
    </script>
{% endblock %}

admin/templates/admin_operate_log_list.html
{% extends 'admin_base.html' %}
{% from 'macro/page_nav.html' import page_nav %}
{% block content %}
    {% include 'components/admin_nav.html' %}
    {% include 'components/admin_aside_menu.html' %}
    <div class="content-wrapper">
        {% include 'components/flash_messages.html' %}
        <!--内容-->
        <section class="content-header">
            <h1>微电影管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 日志管理</a></li>
                <li class="active">操作日志列表</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <h3 class="box-title">操作日志列表</h3>
                            <div class="box-tools">
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="table_search" class="form-control pull-right"
                                           placeholder="请输入关键字...">

                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <tbody>
                                <tr>
                                    <th>编号</th>
                                    <th>管理员</th>
                                    <th>操作时间</th>
                                    <th>操作原因</th>
                                    <th>操作IP</th>
                                    <th>操作终端</th>
                                </tr>
                                {% for item in page_data.items %}
                                    <tr>
                                        <td>{{ item.id }}</td>
                                        <td>{{ item.username }}</td>
                                        <td>{{ item.created_at }}</td>
                                        <td>{{ item.reason }}</td>
                                        <td>{{ item.ip }}</td>
                                        <td>{{ item.ua }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer clearfix">
                            {{ page_nav(page_data, 'admin.admin_operate_log_list') }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}
{% block js %}
    <script>
        $(() => {
            $('#g-8').addClass('active');
            $('#g-8-1').addClass('active');
        })
    </script>
{% endblock %}