home/views.py
import json
import os
import uuid
from datetime import datetime
from io import BytesIO

from flask import Blueprint, render_template, redirect, url_for, flash, make_response, session, request, Response
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename

from conf import Config
from home.forms import RegisterForm, LoginForm, UserDetailForm, ModifyPasswordForm, CommentForm
from models import User, db, UserLog, Preview, Tag, Movie, Comment, MovieCollect, rd
from utils.decorator import user_login_req
from utils.filters import change_filename
from utils.utils import get_verify_code, user_login_log

home = Blueprint('home', __name__,
                 template_folder='templates/',
                 static_folder='../static/home')


# 登录验证码
@home.route('/code')
def get_code():
    image, code = get_verify_code()
    # 图片以二进制形式写入
    buf = BytesIO()
    image.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    # 把buf_str作为response返回前端，并设置首部字段
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/gif'
    # 将验证码字符串储存在session中
    session['image'] = code
    return response


# 首页
@home.route('/<int:page>/', methods=['GET'])
@home.route('/index/<int:page>/', methods=['GET'])
def index(page=1):
    tags = Tag.query.all()
    page_data = Movie.query

    # 标签
    tid = int(request.args.get('tid', 0))
    if tid != 0:
        page_data = page_data.filter_by(tag_id=tid)
    # 星级
    star = int(request.args.get('star', 0))
    if star != 0:
        page_data = page_data.filter_by(star=star)
    # 时间
    time = int(request.args.get('time', 0))
    if time != 0:
        if time == 1:
            page_data = page_data.order_by(Movie.created_at.desc())
        elif time == 2:
            page_data = page_data.order_by(Movie.created_at.asc())

    # 播放量
    pm = int(request.args.get('pm', 0))
    if pm != 0:
        if pm == 1:
            page_data = page_data.order_by(Movie.play_count.desc())
        elif pm == 2:
            page_data = page_data.order_by(Movie.play_count.asc())

    # 评论量
    cm = int(request.args.get('cm', 0))
    if cm != 0:
        if cm == 1:
            page_data = page_data.order_by(Movie.comment_count.desc())
        elif cm == 2:
            page_data = page_data.order_by(Movie.comment_count.asc())

    page_data = page_data.paginate(page=page, per_page=Config.PER_PAGE)

    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )

    return render_template('home_index.html', tags=tags, p=p, page_data=page_data)


# 搜索
@home.route('/search/<int:page>', methods=['GET'])
def search(page=1):
    key = request.args.get('key', '')
    movie_obj = Movie.query.filter(Movie.name.ilike('%' + key + '%'))
    movie_count = movie_obj.count()
    page_data = movie_obj.order_by(Movie.created_at.desc()).paginate(page=page, per_page=Config.PER_PAGE)
    page_data.key = key
    return render_template('home_search.html', key=key, page_data=page_data, movie_count=movie_count)


# 上映预告
@home.route('/animation/', methods=['GET'])
def animation():
    data = Preview.query.all()
    return render_template('home_animation.html', data=data)


# 电影详情
@home.route('/movie_detail/<int:movie_id>/<int:page>/', methods=['GET', 'POST'])
def movie_detail(movie_id=None, page=1):
    movie_obj = Movie.query.get_or_404(int(movie_id))

    form = CommentForm()
    if form.validate_on_submit():
        if session['user']:
            data = form.data
            comment_obj = Comment(
                content=data['content'],
                movie_id=movie_id,
                user_id=session['user_id'],
            )
            db.session.add(comment_obj)
            movie_obj.comment_count = movie_obj.comment_count + 1
            db.session.add(movie_obj)

            db.session.commit()
            flash('评论成功', 'success')
            return redirect(url_for('home.movie_detail', movie_id=movie_id, page=1))

    movie_obj.play_count = movie_obj.play_count + 1
    db.session.add(movie_obj)
    db.session.commit()

    page_data = Comment.query.filter_by(movie_id=movie_id).order_by(Comment.created_at.desc(),
                                                                    Comment.id.desc()).paginate(page=page,
                                                                                                per_page=Config.PER_PAGE)

    return render_template('home_movie_detail.html', movie_obj=movie_obj, form=form, page_data=page_data)


# 电影详情_弹幕
@home.route('/video/<int:movie_id>/<int:page>/', methods=['GET', 'POST'])
def video(movie_id=None, page=1):
    movie_obj = Movie.query.get_or_404(int(movie_id))

    form = CommentForm()
    if session['user'] and form.validate_on_submit():
        data = form.data
        comment_obj = Comment(
            content=data['content'],
            movie_id=movie_id,
            user_id=session['user_id'],
        )
        db.session.add(comment_obj)
        movie_obj.comment_count = movie_obj.comment_count + 1
        db.session.add(movie_obj)

        db.session.commit()
        flash('评论成功', 'success')
        return redirect(url_for('home.video', movie_id=movie_id, page=1))

    movie_obj.play_count = movie_obj.play_count + 1
    db.session.add(movie_obj)
    db.session.commit()

    page_data = Comment.query.filter_by(movie_id=movie_id).order_by(Comment.created_at.desc(),
                                                                    Comment.id.desc()).paginate(page=page,
                                                                                                per_page=Config.PER_PAGE)

    return render_template('home_video.html', movie_obj=movie_obj, form=form, page_data=page_data)


# 登录
@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user_obj = User.query.filter_by(username=data['username']).first()
        if user_obj is None:
            flash('用户不存在', 'danger')
            return render_template('home_login.html', form=form)
        if not user_obj.check_password(data['password']):
            flash('密码错误', 'danger')
            return render_template('home_login.html', form=form)
        if session.get('image').lower() != data['verify_code'].lower():
            flash('验证码错误！', 'danger')
            return render_template('home_login.html', form=form)
        session['user'] = user_obj.username
        session['user_id'] = user_obj.id

        login_type = 'PC'
        user_login_log_obj = user_login_log(login_type)
        db.session.add(user_login_log_obj)
        db.session.commit()
        return redirect(url_for('home.member_center'))
    return render_template('home_login.html', form=form)


# 退出
@home.route('/logout/', methods=['GET'])
@user_login_req
def logout():
    session.pop('user', None)
    session.pop('user_id', None)
    return redirect(url_for('home.login'))


# 会员注册
@home.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user_obj = User(username=data['username'], password=generate_password_hash(data['password']),
                        email=data['email'], phone=data['phone'], nickname=data['nickname'], uuid=uuid.uuid4().hex)
        try:
            db.session.add(user_obj)
            db.session.commit()
            flash('注册成功！', 'success')
            return redirect(url_for('home.login'))
        except Exception as e:
            flash('注册失败！', 'danger')

    return render_template('home_register.html', form=form)


# 个人中心
@home.route('/member_center/', methods=['GET', 'POST'])
@user_login_req
def member_center():
    form = UserDetailForm()
    user_obj = User.query.get(int(session['user_id']))
    form.avatar.validators = []
    if request.method == 'GET':
        form.info.data = user_obj.info

    if form.validate_on_submit():
        data = form.data

        if form.avatar.data.filename != '':
            file_avatar = secure_filename(form.avatar.data.filename)
            # 如果不存在目录，则创建并授权
            if not os.path.exists(Config.UPLOADS_DIR):
                os.makedirs(Config.UPLOADS_DIR)
                os.chmod(Config.UPLOADS_DIR, 6)

            # 格式化名字并保存文件
            avatar = change_filename(file_avatar)
            form.avatar.data.save(Config.UPLOADS_DIR + 'user/avatar/' + avatar)
            user_obj.avatar = avatar

        email_count = User.query.filter_by(email=data['email']).count()
        if data['email'] != user_obj.email and email_count == 1:
            flash('该邮箱已经存在', 'danger')
            return redirect(url_for('home.member_center'))

        phone_count = User.query.filter_by(phone=data['phone']).count()
        if data['phone'] != user_obj.phone and phone_count == 1:
            flash('该手机号码已经存在', 'danger')
            return redirect(url_for('home.member_center'))

        user_obj.username = session['user']
        user_obj.email = data['email']
        user_obj.phone = data['phone']
        user_obj.info = data['username']
        user_obj.nickname = data['nickname']
        db.session.add(user_obj)
        db.session.commit()
        flash('修改成功！', 'success')
        return redirect(url_for('home.member_center'))

    return render_template('home_member_center.html', form=form, user_obj=user_obj)


# 修改密码
@home.route('/edit_password/', methods=['GET', 'POST'])
@user_login_req
def edit_password():
    form = ModifyPasswordForm()
    if form.validate_on_submit():
        user_obj = User.query.filter_by(username=session['user']).first()
        user_obj.password = generate_password_hash(form.pwd.data)

templates/admin_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}微电影后台管理系统{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='admin/admin/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='admin/fonts/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='admin/ionicons/css/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='admin/admin/dist/css/AdminLTE.min.css') }}">

    <link rel="stylesheet" href="{{ url_for('static',filename='admin/admin/dist/css/skins/_all-skins.min.css') }}">
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static',filename='admin/admin/plugins/datepicker/datepicker3.css') }}">
    <style>
        * {
            font-family: "Microsoft YaHei";
        }

        .table > tbody > tr > td,
        .table > tbody > tr > th,
        .table > tfoot > tr > td,
        .table > tfoot > tr > th,
        .table > thead > tr > td,
        .table > thead > tr > th {
            vertical-align: middle;
            text-align: center;
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    {% block content %}{% endblock %}
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>版本</b> 1.0
        </div>
        <strong>版权 &copy; 2021 归<a href="javascript:;">LGSP</a>.</strong> 所有
    </footer>
    <div class="control-sidebar-bg"></div>
</div>
<script src="{{ url_for('static',filename='admin/admin/plugins/jQuery/jQuery-2.2.0.min.js') }}"></script>
<script src="{{ url_for('static',filename='admin/admin/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='admin/admin/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ url_for('static',filename='admin/admin/plugins/fastclick/fastclick.js') }}"></script>
<script src="{{ url_for('static',filename='admin/admin/dist/js/app.min.js') }}"></script>
<script src="{{ url_for('static',filename='admin/admin/dist/js/demo.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/holder.min.js') }}"></script>
<script src="{{ url_for('static',filename='admin/admin/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<script src="{{ url_for('static',filename='admin/admin/plugins/datepicker/locales/bootstrap-datepicker.zh-CN.js') }}"
        charset="UTF-8"></script>
{% block js %}{% endblock %}
</body>

</html>

templates/home_404.html
<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <title>消失在宇宙星空中的404页面</title>
    <link href="{{ url_for('static', filename='home/404/404.css') }}" rel="stylesheet" type="text/css">
</head>
<body>
<!-- 代码 开始 -->
<div class="fullScreen" id="fullScreen">
    <img class="rotating" src="{{ url_for('static', filename='home/404/spaceman.svg') }}">
    <div class="pagenotfound-text">
        <h1>迷失在太空中！</h1>
        <h2><a href="{{ url_for('home.index', page=1) }}">返回首页</a></h2>
    </div>
    <canvas id="canvas2d"></canvas>
</div>
<script type="text/javascript" src="{{ url_for('static', filename='home/404/404.js') }}"></script>
<!-- 代码 结束 -->
</body>
</html>

templates/home_base.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>{% block title %}微电影{% endblock %}</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css') }}">
    <style>
        body {
            overflow-y: scroll;
        }
        .navbar-brand > img {
            display: inline;
        }
        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--内容-->
{% block content %}{% endblock %}
<!--内容-->
<!--底部-->
<footer>
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    {% block copr %}&copy;&nbsp;2021&nbsp;flask_movie&nbsp;京ICP备 12345678号-9{% endblock %}
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/lazyload/jquery.lazyload.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/holder.min.js') }}"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });
    $('#do_search').click(() => {
        let key = $('#key_movie').val();
        location.href = '{{ url_for("home.search", page=1) }}?key=' + key;
    });

</script>
{% block js %}{% endblock %}
</body>
</html>