home/views.py
import json
import os
import uuid
from datetime import datetime
from io import BytesIO

from flask import Blueprint, render_template, redirect, url_for, flash, make_response, session, request, Response
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename

from conf import Config
from home.forms import RegisterForm, LoginForm, UserDetailForm, ModifyPasswordForm, CommentForm
from models import User, db, UserLog, Preview, Tag, Movie, Comment, MovieCollect, rd
from utils.decorator import user_login_req
from utils.filters import change_filename
from utils.utils import get_verify_code, user_login_log

home = Blueprint('home', __name__,
                 template_folder='templates/',
                 static_folder='../static/home')


# 登录验证码
@home.route('/code')
def get_code():
    image, code = get_verify_code()
    # 图片以二进制形式写入
    buf = BytesIO()
    image.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    # 把buf_str作为response返回前端，并设置首部字段
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/gif'
    # 将验证码字符串储存在session中
    session['image'] = code
    return response


# 首页
@home.route('/<int:page>/', methods=['GET'])
@home.route('/index/<int:page>/', methods=['GET'])
def index(page=1):
    tags = Tag.query.all()
    page_data = Movie.query

    # 标签
    tid = int(request.args.get('tid', 0))
    if tid != 0:
        page_data = page_data.filter_by(tag_id=tid)
    # 星级
    star = int(request.args.get('star', 0))
    if star != 0:
        page_data = page_data.filter_by(star=star)
    # 时间
    time = int(request.args.get('time', 0))
    if time != 0:
        if time == 1:
            page_data = page_data.order_by(Movie.created_at.desc())
        elif time == 2:
            page_data = page_data.order_by(Movie.created_at.asc())

    # 播放量
    pm = int(request.args.get('pm', 0))
    if pm != 0:
        if pm == 1:
            page_data = page_data.order_by(Movie.play_count.desc())
        elif pm == 2:
            page_data = page_data.order_by(Movie.play_count.asc())

    # 评论量
    cm = int(request.args.get('cm', 0))
    if cm != 0:
        if cm == 1:
            page_data = page_data.order_by(Movie.comment_count.desc())
        elif cm == 2:
            page_data = page_data.order_by(Movie.comment_count.asc())

    page_data = page_data.paginate(page=page, per_page=Config.PER_PAGE)

    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )

    return render_template('home_index.html', tags=tags, p=p, page_data=page_data)


# 搜索
@home.route('/search/<int:page>', methods=['GET'])
def search(page=1):
    key = request.args.get('key', '')
    movie_obj = Movie.query.filter(Movie.name.ilike('%' + key + '%'))
    movie_count = movie_obj.count()
    page_data = movie_obj.order_by(Movie.created_at.desc()).paginate(page=page, per_page=Config.PER_PAGE)
    page_data.key = key
    return render_template('home_search.html', key=key, page_data=page_data, movie_count=movie_count)


# 上映预告
@home.route('/animation/', methods=['GET'])
def animation():
    data = Preview.query.all()
    return render_template('home_animation.html', data=data)


# 电影详情
@home.route('/movie_detail/<int:movie_id>/<int:page>/', methods=['GET', 'POST'])
def movie_detail(movie_id=None, page=1):
    movie_obj = Movie.query.get_or_404(int(movie_id))

    form = CommentForm()
    if form.validate_on_submit():
        if session['user']:
            data = form.data
            comment_obj = Comment(
                content=data['content'],
                movie_id=movie_id,
                user_id=session['user_id'],
            )
            db.session.add(comment_obj)
            movie_obj.comment_count = movie_obj.comment_count + 1
            db.session.add(movie_obj)

            db.session.commit()
            flash('评论成功', 'success')
            return redirect(url_for('home.movie_detail', movie_id=movie_id, page=1))

    movie_obj.play_count = movie_obj.play_count + 1
    db.session.add(movie_obj)
    db.session.commit()

    page_data = Comment.query.filter_by(movie_id=movie_id).order_by(Comment.created_at.desc(),
                                                                    Comment.id.desc()).paginate(page=page,
                                                                                                per_page=Config.PER_PAGE)

    return render_template('home_movie_detail.html', movie_obj=movie_obj, form=form, page_data=page_data)


# 电影详情_弹幕
@home.route('/video/<int:movie_id>/<int:page>/', methods=['GET', 'POST'])
def video(movie_id=None, page=1):
    movie_obj = Movie.query.get_or_404(int(movie_id))

    form = CommentForm()
    if session['user'] and form.validate_on_submit():
        data = form.data
        comment_obj = Comment(
            content=data['content'],
            movie_id=movie_id,
            user_id=session['user_id'],
        )
        db.session.add(comment_obj)
        movie_obj.comment_count = movie_obj.comment_count + 1
        db.session.add(movie_obj)

        db.session.commit()
        flash('评论成功', 'success')
        return redirect(url_for('home.video', movie_id=movie_id, page=1))

    movie_obj.play_count = movie_obj.play_count + 1
    db.session.add(movie_obj)
    db.session.commit()

    page_data = Comment.query.filter_by(movie_id=movie_id).order_by(Comment.created_at.desc(),
                                                                    Comment.id.desc()).paginate(page=page,
                                                                                                per_page=Config.PER_PAGE)

    return render_template('home_video.html', movie_obj=movie_obj, form=form, page_data=page_data)


# 登录
@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user_obj = User.query.filter_by(username=data['username']).first()
        if user_obj is None:
            flash('用户不存在', 'danger')
            return render_template('home_login.html', form=form)
        if not user_obj.check_password(data['password']):
            flash('密码错误', 'danger')
            return render_template('home_login.html', form=form)
        if session.get('image').lower() != data['verify_code'].lower():
            flash('验证码错误！', 'danger')
            return render_template('home_login.html', form=form)
        session['user'] = user_obj.username
        session['user_id'] = user_obj.id

        login_type = 'PC'
        user_login_log_obj = user_login_log(login_type)
        db.session.add(user_login_log_obj)
        db.session.commit()
        return redirect(url_for('home.member_center'))
    return render_template('home_login.html', form=form)


# 退出
@home.route('/logout/', methods=['GET'])
@user_login_req
def logout():
    session.pop('user', None)
    session.pop('user_id', None)
    return redirect(url_for('home.login'))


# 会员注册
@home.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user_obj = User(username=data['username'], password=generate_password_hash(data['password']),
                        email=data['email'], phone=data['phone'], nickname=data['nickname'], uuid=uuid.uuid4().hex)
        try:
            db.session.add(user_obj)
            db.session.commit()
            flash('注册成功！', 'success')
            return redirect(url_for('home.login'))
        except Exception as e:
            flash('注册失败！', 'danger')

    return render_template('home_register.html', form=form)


# 个人中心
@home.route('/member_center/', methods=['GET', 'POST'])
@user_login_req
def member_center():
    form = UserDetailForm()
    user_obj = User.query.get(int(session['user_id']))
    form.avatar.validators = []
    if request.method == 'GET':
        form.info.data = user_obj.info

    if form.validate_on_submit():
        data = form.data

        if form.avatar.data.filename != '':
            file_avatar = secure_filename(form.avatar.data.filename)
            # 如果不存在目录，则创建并授权
            if not os.path.exists(Config.UPLOADS_DIR):
                os.makedirs(Config.UPLOADS_DIR)
                os.chmod(Config.UPLOADS_DIR, 6)

            # 格式化名字并保存文件
            avatar = change_filename(file_avatar)
            form.avatar.data.save(Config.UPLOADS_DIR + 'user/avatar/' + avatar)
            user_obj.avatar = avatar

        email_count = User.query.filter_by(email=data['email']).count()
        if data['email'] != user_obj.email and email_count == 1:
            flash('该邮箱已经存在', 'danger')
            return redirect(url_for('home.member_center'))

        phone_count = User.query.filter_by(phone=data['phone']).count()
        if data['phone'] != user_obj.phone and phone_count == 1:
            flash('该手机号码已经存在', 'danger')
            return redirect(url_for('home.member_center'))

        user_obj.username = session['user']
        user_obj.email = data['email']
        user_obj.phone = data['phone']
        user_obj.info = data['username']
        user_obj.nickname = data['nickname']
        db.session.add(user_obj)
        db.session.commit()
        flash('修改成功！', 'success')
        return redirect(url_for('home.member_center'))

    return render_template('home_member_center.html', form=form, user_obj=user_obj)


# 修改密码
@home.route('/edit_password/', methods=['GET', 'POST'])
@user_login_req
def edit_password():
    form = ModifyPasswordForm()
    if form.validate_on_submit():
        user_obj = User.query.filter_by(username=session['user']).first()
        user_obj.password = generate_password_hash(form.pwd.data)

templates/components/admin_aside_menu.html
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ url_for('static',filename='admin/admin/dist/img/user2-160x160.jpg') }}" class="img-circle"
                     alt="User Image">
            </div>
            <div class="pull-left info">
                <p>用户：{{ session['admin'] }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> 在线</a>
            </div>
        </div>
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="搜索...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <ul class="sidebar-menu">
            <li class="header">管理菜单</li>
            <li class="treeview" id="g-1">
                <a href="#">
                    <i class="fa fa-home" aria-hidden="true"></i>
                    <span>首页</span>
                    <span class="label label-primary pull-right">1</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-1-1">
                        <a href="{{ url_for('admin.index') }}">
                            <i class="fa fa-circle-o"></i> 控制面板
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-2">
                <a href="#">
                    <i class="fa fa-tags" aria-hidden="true"></i>
                    <span>标签管理</span>
                    <span class="label label-primary pull-right">2</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-2-1">
                        <a href="{{ url_for('admin.tag_add') }}">
                            <i class="fa fa-circle-o"></i> 添加标签
                        </a>
                    </li>
                    <li id="g-2-2">
                        <a href="{{ url_for('admin.tag_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 标签列表
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-3">
                <a href="#">
                    <i class="fa fa-file-video-o" aria-hidden="true"></i>
                    <span>电影管理</span>
                    <span class="label label-primary pull-right">2</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-3-1">
                        <a href="{{ url_for('admin.movie_add') }}">
                            <i class="fa fa-circle-o"></i> 添加电影
                        </a>
                    </li>
                    <li id="g-3-2">
                        <a href="{{ url_for('admin.movie_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 电影列表
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-4">
                <a href="#">
                    <i class="fa fa-film" aria-hidden="true"></i>
                    <span>预告管理</span>
                    <span class="label label-primary pull-right">2</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-4-1">
                        <a href="{{ url_for('admin.preview_add') }}">
                            <i class="fa fa-circle-o"></i> 添加预告
                        </a>
                    </li>
                    <li id="g-4-2">
                        <a href="{{ url_for('admin.preview_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 预告列表
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-5">
                <a href="#">
                    <i class="fa fa-users" aria-hidden="true"></i>
                    <span>会员管理</span>
                    <span class="label label-primary pull-right">1</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-5-1">
                        <a href="{{ url_for('admin.user_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 会员列表
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-6">
                <a href="#">
                    <i class="fa fa-comments" aria-hidden="true"></i>
                    <span>评论管理</span>
                    <span class="label label-primary pull-right">1</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-6-1">
                        <a href="{{ url_for('admin.comment_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 评论列表
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-7">
                <a href="#">
                    <i class="fa fa-heart" aria-hidden="true"></i>
                    <span>收藏管理</span>
                    <span class="label label-primary pull-right">1</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-7-1">
                        <a href="{{ url_for('admin.movie_collect_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 收藏列表
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-8">
                <a href="#">
                    <i class="fa fa-file-text" aria-hidden="true"></i>
                    <span>日志管理</span>
                    <span class="label label-primary pull-right">3</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-8-1">
                        <a href="{{ url_for('admin.admin_operate_log_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 操作日志列表
                        </a>
                    </li>
                    <li id="g-8-2">
                        <a href="{{ url_for('admin.admin_login_log_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 管理员登录日志列表
                        </a>
                    </li>
                    <li id="g-8-3">
                        <a href="{{ url_for('admin.user_login_log_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 会员登录日志列表
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-9">
                <a href="#">
                    <i class="fa fa-lock" aria-hidden="true"></i>
                    <span>权限管理</span>
                    <span class="label label-primary pull-right">2</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-9-1">
                        <a href="{{ url_for('admin.auth_add') }}">
                            <i class="fa fa-circle-o"></i> 添加权限
                        </a>
                    </li>
                    <li id="g-9-2">
                        <a href="{{ url_for('admin.auth_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 权限列表
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-10">
                <a href="#">
                    <i class="fa fa-user-secret" aria-hidden="true"></i>
                    <span>角色管理</span>
                    <span class="label label-primary pull-right">2</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-10-1">
                        <a href="{{ url_for('admin.role_add') }}">
                            <i class="fa fa-circle-o"></i> 添加角色
                        </a>
                    </li>
                    <li id="g-10-2">
                        <a href="{{ url_for('admin.role_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 角色列表
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview" id="g-11">
                <a href="#">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    <span>管理员管理</span>
                    <span class="label label-primary pull-right">2</span>
                </a>
                <ul class="treeview-menu">
                    <li id="g-11-1">
                        <a href="{{ url_for('admin.admin_add') }}">
                            <i class="fa fa-circle-o"></i> 添加管理员
                        </a>
                    </li>
                    <li id="g-11-2">
                        <a href="{{ url_for('admin.admin_list', page=1) }}">
                            <i class="fa fa-circle-o"></i> 管理员列表
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </section>
</aside>

templates/components/admin_nav.html
<header class="main-header">
    <a href="{{ url_for('admin.index') }}" class="logo">
        <span class="logo-mini">
            <img src="{{ url_for('static',filename='base/images/logo.png') }}" style="height: 40px;width: 40px;">微电影
        </span>
        <span class="logo-lg">
            <img src="{{ url_for('static',filename='base/images/logo.png') }}." style="height: 40px;width: 40px; margin-right: 10px;">微电影
        </span>
    </a>
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">下拉菜单</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ url_for('static',filename='admin/admin/dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ session['admin'] }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="{{ url_for('static',filename='admin/admin/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
                            <p>
                                {{ session['admin'] }}
                                <small>{{ online_time }}</small>
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ url_for('admin.edit_password') }}" class="btn btn-default btn-flat">修改密码</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url_for('admin.logout') }}" class="btn btn-default btn-flat">退出系统</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

templates/components/flash_messages.html
{# flash 消息 #}
<!-- 消息通知区域 -->
{% for category, message in get_flashed_messages(with_categories=True) %}
<div class="alert alert-{{ category }} alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    {% autoescape false %}
    <span>{{ message }}</span>
    {% endautoescape %}
</div>
{% endfor %}
<!-- // 消息通知区域 -->

templates/components/home_nav.html
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index', page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" id="key_movie" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index', page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                {% if not session['user'] %}
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                {% else %}
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.member_center') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->

templates/components/home_user_menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{ url_for('home.member_center') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="m-2" href="{{ url_for('home.edit_password') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{ url_for('home.comments', page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{ url_for('home.login_log', page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{ url_for('home.movie_collect', page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>